# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from tank.platform.qt import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(583, 424)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.wizard = QtGui.QStackedWidget(Dialog)
        self.wizard.setObjectName("wizard")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_11 = QtGui.QLabel(self.page)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.page)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/tk_flame_projectcreate/sg_logo.png"))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtGui.QLabel(self.page)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.page1_new = QtGui.QPushButton(self.page)
        self.page1_new.setObjectName("page1_new")
        self.verticalLayout_2.addWidget(self.page1_new)
        self.page1_existing = QtGui.QPushButton(self.page)
        self.page1_existing.setObjectName("page1_existing")
        self.verticalLayout_2.addWidget(self.page1_existing)
        self.page1_noshotgun = QtGui.QPushButton(self.page)
        self.page1_noshotgun.setObjectName("page1_noshotgun")
        self.verticalLayout_2.addWidget(self.page1_noshotgun)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.wizard.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_12 = QtGui.QLabel(self.page_2)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_11.addWidget(self.label_12)
        spacerItem3 = QtGui.QSpacerItem(20, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem3)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_9 = QtGui.QLabel(self.page_2)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.page2_project_name = QtGui.QLineEdit(self.page_2)
        self.page2_project_name.setObjectName("page2_project_name")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.page2_project_name)
        self.label_18 = QtGui.QLabel(self.page_2)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_18)
        self.page2_description = QtGui.QPlainTextEdit(self.page_2)
        self.page2_description.setObjectName("page2_description")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.page2_description)
        self.label_25 = QtGui.QLabel(self.page_2)
        self.label_25.setObjectName("label_25")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_25)
        self.page2_template = QtGui.QComboBox(self.page_2)
        self.page2_template.setObjectName("page2_template")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.page2_template)
        self.horizontalLayout_11.addLayout(self.formLayout)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        spacerItem5 = QtGui.QSpacerItem(20, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.page2_back = QtGui.QPushButton(self.page_2)
        self.page2_back.setObjectName("page2_back")
        self.horizontalLayout_4.addWidget(self.page2_back)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.page2_create = QtGui.QPushButton(self.page_2)
        self.page2_create.setObjectName("page2_create")
        self.horizontalLayout_4.addWidget(self.page2_create)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.wizard.addWidget(self.page_2)
        self.page_7 = QtGui.QWidget()
        self.page_7.setObjectName("page_7")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtGui.QLabel(self.page_7)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.page3_view = QtGui.QListView(self.page_7)
        self.page3_view.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.page3_view.setResizeMode(QtGui.QListView.Adjust)
        self.page3_view.setSpacing(5)
        self.page3_view.setViewMode(QtGui.QListView.IconMode)
        self.page3_view.setUniformItemSizes(True)
        self.page3_view.setObjectName("page3_view")
        self.verticalLayout_4.addWidget(self.page3_view)
        self.label_8 = QtGui.QLabel(self.page_7)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.page3_back = QtGui.QPushButton(self.page_7)
        self.page3_back.setObjectName("page3_back")
        self.horizontalLayout_3.addWidget(self.page3_back)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.page3_select = QtGui.QPushButton(self.page_7)
        self.page3_select.setObjectName("page3_select")
        self.horizontalLayout_3.addWidget(self.page3_select)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.wizard.addWidget(self.page_7)
        self.verticalLayout.addWidget(self.wizard)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(Dialog)
        self.label.setOpenExternalLinks(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.switch_project = QtGui.QToolButton(Dialog)
        self.switch_project.setObjectName("switch_project")
        self.horizontalLayout.addWidget(self.switch_project)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.wizard.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Create Shotgun Project", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "<big>Do you want to use Shotgun for this Project?</big>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Your flame project xxx is not connected to a project in Shotgun. What would you like to do?", None, QtGui.QApplication.UnicodeUTF8))
        self.page1_new.setText(QtGui.QApplication.translate("Dialog", "Create a new Shotgun Project", None, QtGui.QApplication.UnicodeUTF8))
        self.page1_existing.setText(QtGui.QApplication.translate("Dialog", "Associate it with an existing Project", None, QtGui.QApplication.UnicodeUTF8))
        self.page1_noshotgun.setText(QtGui.QApplication.translate("Dialog", "Don\'t use Shotgun for this Project", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "<big>Create a new Shotgun Project</big>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Project Name", None, QtGui.QApplication.UnicodeUTF8))
        self.page2_project_name.setPlaceholderText(QtGui.QApplication.translate("Dialog", "Project Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Dialog", "Template", None, QtGui.QApplication.UnicodeUTF8))
        self.page2_back.setText(QtGui.QApplication.translate("Dialog", "<< Back", None, QtGui.QApplication.UnicodeUTF8))
        self.page2_create.setText(QtGui.QApplication.translate("Dialog", "Create Project", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "<big>Choose an existing Project</big>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "bla bla bla bla", None, QtGui.QApplication.UnicodeUTF8))
        self.page3_back.setText(QtGui.QApplication.translate("Dialog", "<< Back", None, QtGui.QApplication.UnicodeUTF8))
        self.page3_select.setText(QtGui.QApplication.translate("Dialog", "Pick Project", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "<small>You are connected to <a href=\'https://wintermute.shotgunsoftware.com\'>wintermute.shotgunstudio.com</a></small>", None, QtGui.QApplication.UnicodeUTF8))
        self.switch_project.setText(QtGui.QApplication.translate("Dialog", "Switch to another site", None, QtGui.QApplication.UnicodeUTF8))

from . import resources_rc
